// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MockPayment struct {
	ID            string  `json:"id"`
	PaymentMethod string  `json:"paymentMethod"`
	CardHolder    *string `json:"cardHolder,omitempty"`
	CardNumber    *string `json:"cardNumber,omitempty"`
	PhoneNumber   *string `json:"phoneNumber,omitempty"`
	ExpiryDate    *string `json:"expiryDate,omitempty"`
	Cvv           *string `json:"cvv,omitempty"`
}

type Mutation struct {
}

type Payment struct {
	ID            string  `json:"id"`
	StudentID     string  `json:"studentId"`
	Amount        float64 `json:"amount"`
	Currency      string  `json:"currency"`
	TransactionID string  `json:"transactionId"`
	Status        string  `json:"status"`
	CreatedAt     string  `json:"createdAt"`
}

type Query struct {
}
